---
# tasks file for ansible-role-hp-redfish

- block:

  - name: Figure out if we look for debian, rpm or mac packages
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_os_family }}.yml"


  - name: Fetch Github assets data
    uri:
      url: "https://api.github.com/repos/HewlettPackard/python-redfish-utility/releases/latest"
    register: assets

  - name: set a fact with the url to fetch
    set_fact:
      set_fact_ilorest_pkg_url: "{{ item.browser_download_url }}"
    loop: "{{ assets['json']['assets'] }}"
    when: ilorest_pkg_type in item.name

  - name: set a fact with the name of the package
    set_fact:
      set_fact_ilorest_pkg_name: "{{ item.name }}"
    loop: "{{ assets['json']['assets'] }}"
    when: ilorest_pkg_type in item.name

  - name: get_url package to ansible control node or target host to /tmp
    get_url:
      url: "{{ set_fact_ilorest_pkg_url }}"
      dest: "/tmp/{{ set_fact_ilorest_pkg_name }}"
    delegate_to: "{{ ilorest_delegate_to|default(omit) }}"

  - name: copy RPM to destination when not delegated
    copy:
      src: "/tmp/{{ set_fact_ilorest_pkg_name }}"
      dest: "/tmp/{{ set_fact_ilorest_pkg_name }}"
    when: ilorest_delegate_to is defined
  become: False

- block:

  - name: install ilorest on non-debian with package module
    package:
      name: "/tmp/{{ set_fact_ilorest_pkg_name }}"
      state: present
    when: ansible_os_family != "Debian"

  - name: install ilorest deb file on debian with the apt module
    apt:
      deb: "/tmp/{{ set_fact_ilorest_pkg_name }}"
      state: present
    when: ansible_os_family == "Debian"
  become: True
...
